[package]
name = "html_inspector_css"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
css_inspector.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
