[package]
name = "html_inspector_rules_css"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
html_inspector_core = { path = "../html_inspector_core" }
html_inspector_css = { path = "../html_inspector_css" }
